package model;

public enum MetroEventsEnum {
    OPEN_METROSTATION,
    BUY_METROCARD,
    BUY_METROCARDS_TICKETS,
    SCAN_METROGATE,
    ACTIVATE_METROGATE,
    DEACTIVATE_METROGATE,
    NEW_ALERT
}
